# Generated by Django 5.1.3 on 2024-11-10 15:03

import backend.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_role_name_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="url",
            field=models.URLField(
                max_length=256, null=True, validators=[backend.validators.check_url]
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop",
                to="backend.user",
                validators=[backend.validators.check_shop_role],
            ),
        ),
    ]
