# Generated by Django 5.1.3 on 2024-11-10 16:51

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_shop_url_alter_shop_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="url",
            field=models.URLField(
                blank=True, max_length=256, validators=[backend.validators.check_url]
            ),
        ),
    ]
