# Generated by Django 5.0.7 on 2024-11-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_shop_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="apartment",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
