# Generated by Django 5.0.7 on 2024-11-11 20:27

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_user_is_active_alter_details_image_alter_item_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=255, validators=[backend.validators.check_password]
            ),
        ),
    ]
