# Generated by Django 5.0.7 on 2024-11-11 20:31

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=128, validators=[backend.validators.check_password]
            ),
        ),
    ]
